import { User, Subscription, Payment, Notification } from '../types';

export const MOCK_USER: User = {
  id: 'user_123',
  email: 'john@gymfitness.ng',
  firstName: 'John',
  lastName: 'Okafor',
  businessName: 'GymFitness Lagos',
  phone: '+234 801 234 5678',
  country: 'NG',
  currency: 'NGN',
  preferredGateway: 'paystack',
  role: 'owner',
  createdAt: '2024-01-15T10:00:00Z',
  onboardingCompleted: true,
};

export const MOCK_SUBSCRIPTION: Subscription = {
  id: 'sub_123',
  userId: 'user_123',
  planId: 'growth',
  status: 'active',
  billingCycle: 'monthly',
  currentPeriodStart: '2025-01-01T00:00:00Z',
  currentPeriodEnd: '2025-02-01T00:00:00Z',
  cancelAtPeriodEnd: false,
  memberCount: 85,
  usage: {
    members: 85,
    smsUsed: 450,
    emailsUsed: 1200,
    whatsappUsed: 320,
  },
};

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay_001',
    userId: 'user_123',
    subscriptionId: 'sub_123',
    amount: 80000,
    currency: 'NGN',
    status: 'succeeded',
    gateway: 'paystack',
    method: 'card',
    description: 'Growth Plan - January 2025',
    invoiceUrl: '/invoices/inv_001.pdf',
    createdAt: '2025-01-01T09:00:00Z',
    paidAt: '2025-01-01T09:02:00Z',
  },
  {
    id: 'pay_002',
    userId: 'user_123',
    subscriptionId: 'sub_123',
    amount: 80000,
    currency: 'NGN',
    status: 'succeeded',
    gateway: 'paystack',
    method: 'card',
    description: 'Growth Plan - December 2024',
    invoiceUrl: '/invoices/inv_002.pdf',
    createdAt: '2024-12-01T09:00:00Z',
    paidAt: '2024-12-01T09:01:30Z',
  },
  {
    id: 'pay_003',
    userId: 'user_123',
    subscriptionId: 'sub_123',
    amount: 45000,
    currency: 'NGN',
    status: 'succeeded',
    gateway: 'paystack',
    method: 'bank_transfer',
    description: 'Starter Plan - November 2024',
    invoiceUrl: '/invoices/inv_003.pdf',
    createdAt: '2024-11-01T09:00:00Z',
    paidAt: '2024-11-01T10:15:00Z',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_001',
    userId: 'user_123',
    type: 'limit_warning',
    title: 'Approaching Member Limit',
    message: 'You have 85/100 members. Consider upgrading to Pro for 200 members.',
    read: false,
    actionUrl: '/dashboard/plans',
    actionLabel: 'Upgrade Plan',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    channels: ['in_app', 'email'],
  },
  {
    id: 'notif_002',
    userId: 'user_123',
    type: 'payment_success',
    title: 'Payment Successful',
    message: 'Your payment of ₦80,000 for Growth Plan was successful.',
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    channels: ['in_app', 'email', 'sms'],
  },
];