import {
  Enterprise,
  SubscriptionPlan,
  Member,
  Payment,
  PaymentReminder,
  ReminderTemplate,
  EnterpriseAnalytics,
  MemberGrowth,
  RevenueByMonth,
  PlanDistribution,
  EnterpriseNotification,
} from '../../types/enterprise';

// Current Enterprise
export const CURRENT_ENTERPRISE: Enterprise = {
  id: 'ent_001',
  name: 'FitLife Gym Lagos',
  email: 'admin@fitlifegym.ng',
  phone: '+234 801 234 5678',
  address: '45 Admiralty Way, Lekki Phase 1, Lagos',
  website: 'https://fitlifegym.ng',
  currency: 'NGN',
  preferredGateway: 'paystack',
  createdAt: '2023-01-15',
  ownerId: 'user_001',
};

// Subscription Plans
export const MOCK_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan_001',
    enterpriseId: 'ent_001',
    name: 'Basic Membership',
    description: 'Access to gym equipment and basic facilities',
    price: 15000,
    currency: 'NGN',
    duration: 'monthly',
    features: [
      { id: 'f1', name: 'Gym Equipment Access', included: true },
      { id: 'f2', name: 'Locker Room Access', included: true },
      { id: 'f3', name: 'Personal Trainer', included: false },
      { id: 'f4', name: 'Group Classes', included: false },
      { id: 'f5', name: 'Nutrition Consultation', included: false },
    ],
    visibility: 'public',
    isActive: true,
    memberCount: 125,
    createdAt: '2023-01-20',
    updatedAt: '2024-06-15',
  },
  {
    id: 'plan_002',
    enterpriseId: 'ent_001',
    name: 'Premium Membership',
    description: 'Full access with personal training sessions',
    price: 35000,
    currency: 'NGN',
    duration: 'monthly',
    features: [
      { id: 'f1', name: 'Gym Equipment Access', included: true },
      { id: 'f2', name: 'Locker Room Access', included: true },
      { id: 'f3', name: 'Personal Trainer (4 sessions/month)', included: true },
      { id: 'f4', name: 'Group Classes', included: true },
      { id: 'f5', name: 'Nutrition Consultation', included: true },
    ],
    visibility: 'public',
    isActive: true,
    memberCount: 78,
    createdAt: '2023-01-20',
    updatedAt: '2024-08-10',
  },
  {
    id: 'plan_003',
    enterpriseId: 'ent_001',
    name: 'VIP Membership',
    description: 'Exclusive access with unlimited perks',
    price: 75000,
    currency: 'NGN',
    duration: 'monthly',
    features: [
      { id: 'f1', name: 'Gym Equipment Access', included: true },
      { id: 'f2', name: 'Private Locker', included: true },
      { id: 'f3', name: 'Personal Trainer (Unlimited)', included: true },
      { id: 'f4', name: 'All Group Classes', included: true },
      { id: 'f5', name: 'Monthly Nutrition Consultation', included: true },
      { id: 'f6', name: 'Spa & Sauna Access', included: true },
      { id: 'f7', name: 'Guest Passes (2/month)', included: true },
    ],
    visibility: 'invite_only',
    isActive: true,
    memberCount: 23,
    createdAt: '2023-03-10',
    updatedAt: '2024-09-05',
  },
  {
    id: 'plan_004',
    enterpriseId: 'ent_001',
    name: 'Student Plan',
    description: 'Discounted membership for students',
    price: 10000,
    currency: 'NGN',
    duration: 'monthly',
    features: [
      { id: 'f1', name: 'Gym Equipment Access', included: true },
      { id: 'f2', name: 'Locker Room Access', included: true },
      { id: 'f3', name: 'Personal Trainer', included: false },
      { id: 'f4', name: 'Group Classes (2/week)', included: true },
    ],
    visibility: 'public',
    isActive: true,
    memberCount: 47,
    createdAt: '2023-09-01',
    updatedAt: '2024-09-01',
  },
];

// Members
export const MOCK_MEMBERS: Member[] = [
  {
    id: 'mem_001',
    enterpriseId: 'ent_001',
    userId: 'user_101',
    name: 'Chidi Okonkwo',
    email: 'chidi.okonkwo@email.com',
    phone: '+234 801 234 5678',
    planId: 'plan_002',
    planName: 'Premium Membership',
    status: 'active',
    membershipType: 'self_signup',
    subscriptionStartDate: '2024-11-01',
    subscriptionExpiryDate: '2025-11-01',
    autoRenew: true,
    lastPaymentDate: '2024-11-01',
    totalPaid: 420000,
    joinedDate: '2023-06-15',
    gateway: 'paystack',
  },
  {
    id: 'mem_002',
    enterpriseId: 'ent_001',
    userId: 'user_102',
    name: 'Amara Nwosu',
    email: 'amara.nwosu@email.com',
    phone: '+234 802 345 6789',
    planId: 'plan_001',
    planName: 'Basic Membership',
    status: 'active',
    membershipType: 'self_signup',
    subscriptionStartDate: '2024-12-15',
    subscriptionExpiryDate: '2025-01-15',
    autoRenew: true,
    lastPaymentDate: '2024-12-15',
    totalPaid: 180000,
    joinedDate: '2024-01-20',
    gateway: 'paystack',
  },
  {
    id: 'mem_003',
    enterpriseId: 'ent_001',
    userId: 'user_103',
    name: 'Emeka Adeyemi',
    email: 'emeka.adeyemi@email.com',
    phone: '+234 803 456 7890',
    planId: 'plan_004',
    planName: 'Student Plan',
    status: 'inactive',
    membershipType: 'manual_add',
    subscriptionStartDate: '2024-08-01',
    subscriptionExpiryDate: '2024-12-01',
    autoRenew: false,
    lastPaymentDate: '2024-08-01',
    totalPaid: 40000,
    joinedDate: '2024-08-01',
    gateway: 'paystack',
  },
  {
    id: 'mem_004',
    enterpriseId: 'ent_001',
    userId: 'user_104',
    name: 'Funke Ajayi',
    email: 'funke.ajayi@email.com',
    phone: '+234 804 567 8901',
    planId: 'plan_003',
    planName: 'VIP Membership',
    status: 'active',
    membershipType: 'invite',
    subscriptionStartDate: '2025-01-01',
    subscriptionExpiryDate: '2026-01-01',
    autoRenew: true,
    lastPaymentDate: '2025-01-01',
    totalPaid: 900000,
    joinedDate: '2022-03-10',
    gateway: 'stripe',
  },
  {
    id: 'mem_005',
    enterpriseId: 'ent_001',
    userId: 'user_105',
    name: 'Tunde Bakare',
    email: 'tunde.bakare@email.com',
    phone: '+234 805 678 9012',
    planId: 'plan_001',
    planName: 'Basic Membership',
    status: 'expired',
    membershipType: 'self_signup',
    subscriptionStartDate: '2024-06-01',
    subscriptionExpiryDate: '2024-12-01',
    autoRenew: false,
    lastPaymentDate: '2024-06-01',
    totalPaid: 90000,
    joinedDate: '2024-06-01',
    gateway: 'paystack',
  },
];

// Payments - Enhanced with memberEmail field
export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay_001',
    enterpriseId: 'ent_001',
    memberId: 'mem_001',
    memberName: 'Chidi Okonkwo',
    memberEmail: 'chidi.okonkwo@email.com',
    planId: 'plan_002',
    planName: 'Premium Membership',
    amount: 35000,
    currency: 'NGN',
    status: 'success',
    method: 'card',
    reference: 'REF_20250101_001',
    description: 'Premium Membership - January 2025',
    gateway: 'paystack',
    isAutoRenewal: true,
    createdAt: '2025-01-01T09:00:00Z',
    paidAt: '2025-01-01T09:02:15Z',
  },
  {
    id: 'pay_002',
    enterpriseId: 'ent_001',
    memberId: 'mem_002',
    memberName: 'Amara Nwosu',
    memberEmail: 'amara.nwosu@email.com',
    planId: 'plan_001',
    planName: 'Basic Membership',
    amount: 15000,
    currency: 'NGN',
    status: 'success',
    method: 'bank_transfer',
    reference: 'REF_20241215_002',
    description: 'Basic Membership - December 2024',
    gateway: 'paystack',
    isAutoRenewal: true,
    createdAt: '2024-12-15T10:30:00Z',
    paidAt: '2024-12-15T11:45:00Z',
  },
  {
    id: 'pay_003',
    enterpriseId: 'ent_001',
    memberId: 'mem_004',
    memberName: 'Funke Ajayi',
    memberEmail: 'funke.ajayi@email.com',
    planId: 'plan_003',
    planName: 'VIP Membership',
    amount: 75000,
    currency: 'NGN',
    status: 'success',
    method: 'card',
    reference: 'REF_20250101_003',
    description: 'VIP Membership - January 2025',
    gateway: 'stripe',
    isAutoRenewal: true,
    createdAt: '2025-01-01T08:00:00Z',
    paidAt: '2025-01-01T08:01:30Z',
  },
  {
    id: 'pay_004',
    enterpriseId: 'ent_001',
    memberId: 'mem_001',
    memberName: 'Chidi Okonkwo',
    memberEmail: 'chidi.okonkwo@email.com',
    planId: 'plan_002',
    planName: 'Premium Membership',
    amount: 35000,
    currency: 'NGN',
    status: 'success',
    method: 'card',
    reference: 'REF_20241201_004',
    description: 'Premium Membership - December 2024',
    gateway: 'paystack',
    isAutoRenewal: true,
    createdAt: '2024-12-01T09:00:00Z',
    paidAt: '2024-12-01T09:02:00Z',
  },
  {
    id: 'pay_005',
    enterpriseId: 'ent_001',
    memberId: 'mem_002',
    memberName: 'Amara Nwosu',
    memberEmail: 'amara.nwosu@email.com',
    planId: 'plan_001',
    planName: 'Basic Membership',
    amount: 15000,
    currency: 'NGN',
    status: 'success',
    method: 'bank_transfer',
    reference: 'REF_20241115_005',
    description: 'Basic Membership - November 2024',
    gateway: 'paystack',
    isAutoRenewal: true,
    createdAt: '2024-11-15T10:30:00Z',
    paidAt: '2024-11-15T12:00:00Z',
  },
  {
    id: 'pay_006',
    enterpriseId: 'ent_001',
    memberId: 'mem_004',
    memberName: 'Funke Ajayi',
    memberEmail: 'funke.ajayi@email.com',
    planId: 'plan_003',
    planName: 'VIP Membership',
    amount: 75000,
    currency: 'NGN',
    status: 'success',
    method: 'card',
    reference: 'REF_20241201_006',
    description: 'VIP Membership - December 2024',
    gateway: 'stripe',
    isAutoRenewal: true,
    createdAt: '2024-12-01T08:00:00Z',
    paidAt: '2024-12-01T08:01:45Z',
  },
  {
    id: 'pay_007',
    enterpriseId: 'ent_001',
    memberId: 'mem_003',
    memberName: 'Emeka Adeyemi',
    memberEmail: 'emeka.adeyemi@email.com',
    planId: 'plan_004',
    planName: 'Student Plan',
    amount: 10000,
    currency: 'NGN',
    status: 'success',
    method: 'ussd',
    reference: 'REF_20241001_007',
    description: 'Student Plan - October 2024',
    gateway: 'paystack',
    isAutoRenewal: false,
    createdAt: '2024-10-01T14:00:00Z',
    paidAt: '2024-10-01T14:15:30Z',
  },
  {
    id: 'pay_008',
    enterpriseId: 'ent_001',
    memberId: 'mem_005',
    memberName: 'Tunde Bakare',
    memberEmail: 'tunde.bakare@email.com',
    planId: 'plan_001',
    planName: 'Basic Membership',
    amount: 15000,
    currency: 'NGN',
    status: 'success',
    method: 'bank_transfer',
    reference: 'MANUAL_20241105_008',
    description: 'Basic Membership - November 2024 (Manual Log)',
    isAutoRenewal: false,
    createdAt: '2024-11-05T10:00:00Z',
    paidAt: '2024-11-05T10:00:00Z',
  },
  {
    id: 'pay_009',
    enterpriseId: 'ent_001',
    memberId: 'mem_001',
    memberName: 'Chidi Okonkwo',
    memberEmail: 'chidi.okonkwo@email.com',
    planId: 'plan_002',
    planName: 'Premium Membership',
    amount: 35000,
    currency: 'NGN',
    status: 'success',
    method: 'card',
    reference: 'REF_20241101_009',
    description: 'Premium Membership - November 2024',
    gateway: 'paystack',
    isAutoRenewal: true,
    createdAt: '2024-11-01T09:00:00Z',
    paidAt: '2024-11-01T09:02:30Z',
  },
  {
    id: 'pay_010',
    enterpriseId: 'ent_001',
    memberId: 'mem_004',
    memberName: 'Funke Ajayi',
    memberEmail: 'funke.ajayi@email.com',
    planId: 'plan_003',
    planName: 'VIP Membership',
    amount: 75000,
    currency: 'NGN',
    status: 'success',
    method: 'card',
    reference: 'REF_20241101_010',
    description: 'VIP Membership - November 2024',
    gateway: 'stripe',
    isAutoRenewal: true,
    createdAt: '2024-11-01T08:00:00Z',
    paidAt: '2024-11-01T08:01:20Z',
  },
  {
    id: 'pay_011',
    enterpriseId: 'ent_001',
    memberId: 'mem_002',
    memberName: 'Amara Nwosu',
    memberEmail: 'amara.nwosu@email.com',
    planId: 'plan_001',
    planName: 'Basic Membership',
    amount: 15000,
    currency: 'NGN',
    status: 'pending',
    method: 'bank_transfer',
    reference: 'MANUAL_20250103_011',
    description: 'Basic Membership - January 2025 (Pending Verification)',
    isAutoRenewal: false,
    createdAt: '2025-01-03T11:00:00Z',
  },
  {
    id: 'pay_012',
    enterpriseId: 'ent_001',
    memberId: 'mem_003',
    memberName: 'Emeka Adeyemi',
    memberEmail: 'emeka.adeyemi@email.com',
    planId: 'plan_004',
    planName: 'Student Plan',
    amount: 10000,
    currency: 'NGN',
    status: 'failed',
    method: 'card',
    reference: 'REF_20241220_012',
    description: 'Student Plan - December 2024 (Payment Failed)',
    gateway: 'paystack',
    isAutoRenewal: false,
    createdAt: '2024-12-20T15:30:00Z',
  },
  {
    id: 'pay_013',
    enterpriseId: 'ent_001',
    memberId: 'mem_005',
    memberName: 'Tunde Bakare',
    memberEmail: 'tunde.bakare@email.com',
    planId: 'plan_001',
    planName: 'Basic Membership',
    amount: 15000,
    currency: 'NGN',
    status: 'success',
    method: 'ussd',
    reference: 'REF_20241001_013',
    description: 'Basic Membership - October 2024',
    gateway: 'paystack',
    isAutoRenewal: false,
    createdAt: '2024-10-01T12:00:00Z',
    paidAt: '2024-10-01T12:30:00Z',
  },
  {
    id: 'pay_014',
    enterpriseId: 'ent_001',
    memberId: 'mem_001',
    memberName: 'Chidi Okonkwo',
    memberEmail: 'chidi.okonkwo@email.com',
    planId: 'plan_002',
    planName: 'Premium Membership',
    amount: 35000,
    currency: 'NGN',
    status: 'success',
    method: 'card',
    reference: 'REF_20241001_014',
    description: 'Premium Membership - October 2024',
    gateway: 'paystack',
    isAutoRenewal: true,
    createdAt: '2024-10-01T09:00:00Z',
    paidAt: '2024-10-01T09:02:10Z',
  },
  {
    id: 'pay_015',
    enterpriseId: 'ent_001',
    memberId: 'mem_004',
    memberName: 'Funke Ajayi',
    memberEmail: 'funke.ajayi@email.com',
    planId: 'plan_003',
    planName: 'VIP Membership',
    amount: 75000,
    currency: 'NGN',
    status: 'success',
    method: 'card',
    reference: 'REF_20241001_015',
    description: 'VIP Membership - October 2024',
    gateway: 'stripe',
    isAutoRenewal: true,
    createdAt: '2024-10-01T08:00:00Z',
    paidAt: '2024-10-01T08:01:15Z',
  },
];

// Payment Reminders
export const MOCK_REMINDERS: PaymentReminder[] = [
  {
    id: 'rem_001',
    enterpriseId: 'ent_001',
    memberId: 'mem_005',
    memberName: 'Tunde Bakare',
    memberEmail: 'tunde.bakare@email.com',
    type: 'subscription_expiring',
    status: 'sent',
    channels: ['email', 'sms'],
    scheduledFor: '2024-11-25T09:00:00Z',
    sentAt: '2024-11-25T09:00:15Z',
    message: 'Your subscription expires in 7 days. Renew now to continue enjoying our services.',
  },
  {
    id: 'rem_002',
    enterpriseId: 'ent_001',
    memberId: 'mem_002',
    memberName: 'Amara Nwosu',
    memberEmail: 'amara.nwosu@email.com',
    type: 'payment_due',
    status: 'pending',
    channels: ['email', 'whatsapp'],
    scheduledFor: '2025-01-08T09:00:00Z',
    message: 'Your payment is due in 7 days. Please ensure your payment method is up to date.',
  },
];

// Reminder Templates
export const MOCK_REMINDER_TEMPLATES: ReminderTemplate[] = [
  {
    id: 'temp_001',
    enterpriseId: 'ent_001',
    type: 'subscription_expiring',
    subject: 'Your Membership is Expiring Soon',
    message: 'Hi {member_name}, your {plan_name} subscription expires on {expiry_date}. Renew now to avoid service interruption.',
    channels: ['email', 'sms'],
    isActive: true,
  },
  {
    id: 'temp_002',
    enterpriseId: 'ent_001',
    type: 'payment_failed',
    subject: 'Payment Failed - Action Required',
    message: 'Hi {member_name}, we were unable to process your payment for {plan_name}. Please update your payment method.',
    channels: ['email', 'sms', 'whatsapp'],
    isActive: true,
  },
  {
    id: 'temp_003',
    enterpriseId: 'ent_001',
    type: 'welcome',
    subject: 'Welcome to FitLife Gym!',
    message: 'Hi {member_name}, welcome to FitLife Gym! Your {plan_name} subscription is now active. We look forward to seeing you!',
    channels: ['email'],
    isActive: true,
  },
];

// Analytics
export const MOCK_ANALYTICS: EnterpriseAnalytics = {
  totalMembers: 273,
  activeMembers: 203,
  inactiveMembers: 45,
  expiredMembers: 25,
  newMembersThisMonth: 18,
  totalRevenue: 8750000,
  monthlyRevenue: 7250000,
  revenueGrowth: 15.5,
  averageRevenuePerMember: 32051,
};

// Member Growth Data
export const MOCK_MEMBER_GROWTH: MemberGrowth[] = [
  { month: 'Jan', newMembers: 12, totalMembers: 185, active: 165, inactive: 20 },
  { month: 'Feb', newMembers: 18, totalMembers: 203, active: 178, inactive: 25 },
  { month: 'Mar', newMembers: 15, totalMembers: 218, active: 190, inactive: 28 },
  { month: 'Apr', newMembers: 22, totalMembers: 240, active: 210, inactive: 30 },
  { month: 'May', newMembers: 20, totalMembers: 260, active: 228, inactive: 32 },
  { month: 'Jun', newMembers: 13, totalMembers: 273, active: 203, inactive: 45 },
];

// Revenue Data
export const MOCK_REVENUE_DATA: RevenueByMonth[] = [
  { month: 'Jan', revenue: 5500000, previousYear: 4200000, memberCount: 185 },
  { month: 'Feb', revenue: 6100000, previousYear: 4800000, memberCount: 203 },
  { month: 'Mar', revenue: 6450000, previousYear: 5100000, memberCount: 218 },
  { month: 'Apr', revenue: 6900000, previousYear: 5400000, memberCount: 240 },
  { month: 'May', revenue: 7100000, previousYear: 5700000, memberCount: 260 },
  { month: 'Jun', revenue: 7250000, previousYear: 6000000, memberCount: 273 },
];

// Plan Distribution
export const MOCK_PLAN_DISTRIBUTION: PlanDistribution[] = [
  { planId: 'plan_001', planName: 'Basic Membership', memberCount: 125, revenue: 1875000, percentage: 45.8 },
  { planId: 'plan_002', planName: 'Premium Membership', memberCount: 78, revenue: 2730000, percentage: 28.6 },
  { planId: 'plan_003', planName: 'VIP Membership', memberCount: 23, revenue: 1725000, percentage: 8.4 },
  { planId: 'plan_004', planName: 'Student Plan', memberCount: 47, revenue: 470000, percentage: 17.2 },
];

// Notifications
export const MOCK_NOTIFICATIONS: EnterpriseNotification[] = [
  {
    id: 'notif_001',
    enterpriseId: 'ent_001',
    type: 'payment_received',
    title: 'New Payment Received',
    message: 'Chidi Okonkwo paid ₦35,000 for Premium Membership',
    memberId: 'mem_001',
    memberName: 'Chidi Okonkwo',
    read: false,
    createdAt: '2025-01-01T09:02:15Z',
    link: '/enterprise/members/mem_001',
  },
  {
    id: 'notif_002',
    enterpriseId: 'ent_001',
    type: 'subscription_expiring',
    title: 'Subscription Expiring Soon',
    message: 'Amara Nwosu subscription expires in 10 days',
    memberId: 'mem_002',
    memberName: 'Amara Nwosu',
    read: false,
    createdAt: '2025-01-05T08:00:00Z',
    link: '/enterprise/members/mem_002',
  },
  {
    id: 'notif_003',
    enterpriseId: 'ent_001',
    type: 'new_member',
    title: 'New Member Joined',
    message: 'Ibrahim Musa joined with Student Plan',
    memberId: 'mem_007',
    memberName: 'Ibrahim Musa',
    read: true,
    createdAt: '2025-01-03T14:30:00Z',
    link: '/enterprise/members/mem_007',
  },
];